etcd:
  version: 3.2.27
  advertise_client_urls:       "http://{PRIVATE_IPV4}:2379"
  initial_advertise_peer_urls: "http://{PRIVATE_IPV4}:2380"
  listen_client_urls:          "http://0.0.0.0:2379"
  listen_peer_urls:            "http://{PRIVATE_IPV4}:2380"
  discovery:                   "https://discovery.etcd.io/<token>"

flannel:
  # linux-container-config-transpiler only support up to 0.7.0
  # most recent in stable is 0.11.0
  # 0.7.0 does not work with docker version of stable (no inter node traffic possible)
  # leave flannel version floating for now
  # version: 0.7.0
  network_config: '{"Network": "10.1.0.0/16"}'
  public_ip: "{PRIVATE_IPV4}"

# storage:
#   files:
#   - filesystem: "root"
#     path: "/opt/bin/mc"
#     mode: 0755
#     contents:
#       source: "https://example.com/metadata-script.sh"
#       verification:
#         hash: sha512-...  # <type>-<value>

systemd:
  units:
  - name: mc.service
    enable: true
    contents: |
      [Unit]
      Description=MoltenCore
      Requires=etcd-member.service flanneld.service coreos-metadata.service
      After=etcd-member.service flanneld.service coreos-metadata.service

      [Service]
      Type=oneshot
      ExecStart=/opt/bin/mc init
      RemainAfterExit=true
      StandardOutput=journal
      User=root

      [Install]
      WantedBy=multi-user.target docker.service
