etcd:
  advertise_client_urls: http://{PRIVATE_IPV4}:2379
  discovery: https://discovery.etcd.io/<token>
  initial_advertise_peer_urls: http://{PRIVATE_IPV4}:2380
  listen_client_urls: http://0.0.0.0:2379
  listen_peer_urls: http://{PRIVATE_IPV4}:2380
  version: 3.2.27
flannel:
  network_config: '{"Network": "10.1.0.0/16"}'
  public_ip: '{PRIVATE_IPV4}'
storage:
  files:
  - contents:
      remote:
        url: https://github.com/starkandwayne/molten-core/releases/download/v0.0.1/mc
        verification:
          hash:
            function: sha512
            sum: 4d87e5860f66f0325def57d784609da3461139f559bc37fc337b130b7f2a0fc5f420dce0674d5bb1cfdf6bfc39778e9b8d6ecf0339e57352ca244aa703d7b900
    filesystem: root
    mode: 493
    path: /opt/bin/mc
systemd:
  units:
  - contents: |
      [Unit]
      Description=MoltenCore
      Requires=etcd-member.service flanneld.service coreos-metadata.service
      After=etcd-member.service flanneld.service coreos-metadata.service

      [Service]
      Type=oneshot
      ExecStart=/opt/bin/mc init
      RemainAfterExit=true
      StandardOutput=journal
      User=root

      [Install]
      WantedBy=multi-user.target docker.service
    enable: true
    name: mc.service
