etcd:
  advertise_client_urls: http://{PRIVATE_IPV4}:2379
  discovery: https://discovery.etcd.io/<token>
  initial_advertise_peer_urls: http://{PRIVATE_IPV4}:2380
  listen_client_urls: http://0.0.0.0:2379
  listen_peer_urls: http://{PRIVATE_IPV4}:2380
  version: 3.2.27
flannel:
  network_config: '{"Network": "10.1.0.0/16"}'
  public_ip: '{PRIVATE_IPV4}'
storage:
  files:
  - contents:
      remote:
        url: https://github.com/starkandwayne/molten-core/releases/download/v0.2.0/mc
        verification:
          hash:
            function: sha512
            sum: f046fcde18b780bf344799e7a6b01dfca352448571e36bb484e42eb37369bd8e1bf42780509240469f5ff5e8f55b6351f2519f4d675eace8f07e67a0ab1d6241
    filesystem: root
    mode: 493
    path: /opt/bin/mc
systemd:
  units:
  - contents: |
      [Unit]
      Description=MoltenCore
      Requires=etcd-member.service flanneld.service coreos-metadata.service
      After=etcd-member.service flanneld.service coreos-metadata.service

      [Service]
      Type=oneshot
      ExecStart=/opt/bin/mc init
      RemainAfterExit=true
      StandardOutput=journal
      User=root

      [Install]
      WantedBy=multi-user.target docker.service
    enable: true
    name: mc.service
