etcd:
  advertise_client_urls: http://{PRIVATE_IPV4}:2379
  discovery: ETCD_DISCOVERY_PLACEHOLDER
  initial_advertise_peer_urls: http://{PRIVATE_IPV4}:2380
  listen_client_urls: http://0.0.0.0:2379
  listen_peer_urls: http://{PRIVATE_IPV4}:2380
  version: 3.2.27
storage:
  files:
  - contents:
      remote:
        url: https://github.com/starkandwayne/molten-core/releases/download/v0.7.0/mc
        verification:
          hash:
            function: sha512
            sum: 3805573abd7279ad890d9d0a742d741f460a6f97657d9aba040c82e20a50b4f7641de2525dfe36c471644be4a4f7b96e1ac1fe87342ba60f7fad1c498aed0f16
    filesystem: root
    mode: 755
    path: /opt/bin/mc
systemd:
  units:
  - contents: |
      [Unit]
      Description=MoltenCore
      Requires=etcd-member.service coreos-metadata.service
      After=etcd-member.service coreos-metadata.service

      [Service]
      Type=oneshot
      ExecStart=/opt/bin/mc init --zone=MC_ZONE_PLACEHOLDER
      RemainAfterExit=true
      StandardOutput=journal
      User=root

      [Install]
      WantedBy=multi-user.target docker.service flanneld.service
    enable: true
    name: mc.service
  - mask: true
    name: update-engine.service
  - mask: true
    name: locksmithd.service
