#!/bin/bash -e

ct -out-file ../coreos-vagrant/config.ign \
   -platform vagrant-virtualbox -pretty -strict \
   -in-file <(bosh int container-linux-config.yaml \
                   -o <(echo '[{"type":"remove","path":"/storage"}]'))

if [ -d "../coreos-vagrant" ]; then
  echo "Please clone the following repo: https://github.com/coreos/coreos-vagrant in ../coreos-vagrant"
fi

pushd ../coreos-vagrant
cat <<EOF > config.rb
# Size of the CoreOS cluster created by Vagrant
\$num_instances=3

# Official CoreOS channel from which updates should be downloaded
\$update_channel='stable'
\$vm_memory = 6144

\$new_discovery_url="https://discovery.etcd.io/new?size=#{\$num_instances}"

if ARGV[0].eql?('up')
  require 'open-uri'
  token = open(\$new_discovery_url).read
  data = File.read('config.ign')
  data.gsub!(/MC_ZONE_PLACEHOLDER/, "0 --dev")
  data.gsub!(/ETCD_DISCOVERY_PLACEHOLDER/, token)
  File.open('config.ign', 'w') { |file| file.write(data) }
end
EOF

vagrant up --parallel
popd
