#!/bin/bash -e

tmpVDI=/tmp/cloned.vdi
boxName=coreos-stable
resizeTo=35000

diskUUID() {
    VBoxManage list hdds | grep -B4 ${1} | grep -e '^UUID' | awk 'END {print $2}'
}

for vmdk in $(find ~/.vagrant.d/boxes/${boxName} | grep vmdk); do
    VBoxManage clonemedium ${vmdk} ${tmpVDI} --format vdi
    VBoxManage closemedium disk $(diskUUID ${vmdk}) --delete
    VBoxManage modifymedium ${tmpVDI} --resize ${resizeTo}
    VBoxManage clonemedium ${tmpVDI} ${vmdk} --format vmdk
    VBoxManage closemedium disk $(diskUUID ${vmdk})
    VBoxManage closemedium disk $(diskUUID ${tmpVDI}) --delete
done
