jobs:
- name: deploy-cf
  plan:
  - in_parallel:
    - get: cf-deployment
      trigger: true
    - get: stemcell
    - get: opsfile
  - put: deploy
    params:
      manifest: cf-deployment/cf-deployment.yml
      stemcells: [ stemcell/stemcell.tgz ]
      ops_files:
      - cf-deployment/operations/use-compiled-releases.yml
      - cf-deployment/operations/use-latest-stemcell.yml
      - cf-deployment/operations/scale-to-one-az.yml
      - opsfile/opsfile.yml
      vars:
        system_domain: ((moltencore.public_ips.0)).xip.io
resources:
- name: opsfile
  type: file
  source:
    filename: opsfile.yml
    content:
      # Docker garden compatibility
      - type: replace
        path: /instance_groups/name=diego-cell/jobs/name=garden/properties/garden/apparmor_profile?
        value: ""
      - type: replace
        path: /instance_groups/name=diego-cell/jobs/name=rep/properties?/set_kernel_parameters
        value: false
      - type: replace
        path: /instance_groups/name=diego-api/jobs/name=bbs/properties?/set_kernel_parameters
        value: false
      - type: replace
        path: /instance_groups/name=api/jobs/name=file_server/properties?/set_kernel_parameters
        value: false
      - type: replace
        path: /instance_groups/name=diego-api/jobs/name=locket/properties?/set_kernel_parameters
        value: false

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git
    branch: master
    tag_filter: v*

- name: deploy
  type: bosh-deployment
  source:
    deployment: cf
    target: ((bosh_environment))
    client: ((bosh_client))
    client_id: ((bosh_client))
    client_secret: ((bosh_client_secret))
    ca_cert: ((bosh_ca_cert))

- name: stemcell
  type: bosh-io-stemcell
  source: { name: ((bosh_stemcell)) }

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: latest

- name: file
  type: docker-image
  source:
    repository: aequitas/concourse-file-resource
    tag: latest
